version: '2.1'

services:
  webreactjs:
    image: myweb
    container_name: "webreactjs"
    build: .
    ports:
      - 3000:3000
    restart: always
  servergo:
    image: myserver
    container_name: "servergo"
    build: .
    ports:
      - 8080:8080
    restart: always
