apiVersion: v1
kind: Service
metadata:
  name: nodejs-devops
spec:
  selector:
    app: nodejs-devops
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30300
  type: NodePort