apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.service.type: LoadBalancer
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: bulletinapi
  name: bulletinapi
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: bulletinapi
    spec:
      containers:
      - env:
        - name: GET_HOSTS_FROM
          value: dns
        image: kisulken/bulletinapi:v1
        name: bulletinapi
        ports:
        - containerPort: 8080
        resources: {}
        volumeMounts:
        - mountPath: /go/src/bulletinApi
          name: bulletinapi-claim0
      hostname: bulletinapi
      restartPolicy: Always
      volumes:
      - name: bulletinapi-claim0
        persistentVolumeClaim:
          claimName: bulletinapi-claim0
status: {}
